<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.fitme">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.FitMe">
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name=".KnowUserActivity_B"
            android:exported="true"/>
        <activity
            android:name=".ThankYou"
            android:exported="true"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name=".Know_UserActivity"
            android:exported="true"/>
        <activity
            android:name=".notConnected"
            android:exported="true"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name=".CoronaPageActivity"
            android:exported="true"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name=".AffectedCountries"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name=".DetailActivity"/>
        <activity
            android:theme="@style/Base.Theme.AppCompat"
            android:name="com.theartofdev.edmodo.cropper.CropImageActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name=".Delta_Activity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name=".Golf_Activity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.India_Activity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.EchoActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.Motherhood_Fragment"
            android:parentActivityName="com.example.fitme.MainActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.Menstrual_Fragment"
            android:parentActivityName="com.example.fitme.MainActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.Soothing_Fragment"
            android:parentActivityName="com.example.fitme.MainActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.Breathing_Fragment"
            android:parentActivityName="com.example.fitme.MainActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.Morning_Fragment"
            android:parentActivityName="com.example.fitme.MainActivity"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name="com.example.fitme.AboutUs_Activity"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name="com.example.fitme.Profile_Activity"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:label="@string/title_activity_friends"
            android:name="com.example.fitme.Friends_Activity"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name="com.example.fitme.Account_Activity1"/>
        <activity
            android:theme="@style/Theme.FitMe.NoActionBar"
            android:name="com.example.fitme.Reminder_Activity"/>
        <activity
            android:theme="@style/CustomTheme1"
            android:name="com.example.fitme.TrainingDaysActivity"/>
        <activity
            android:theme="@style/CustomTheme1"
            android:name="com.example.fitme.Login_pageActivity"
            android:parentActivityName="com.example.fitme.Main_PageActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.Gym_AdvancedActivity"
            android:parentActivityName="com.example.fitme.Gym_PageActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.Gym_IntermediateActivity"
            android:parentActivityName="com.example.fitme.Gym_PageActivity"/>
        <activity
            android:theme="@style/CustomTheme"
            android:name="com.example.fitme.Gym_BeginnerActivity"
            android:parentActivityName="com.example.fitme.Gym_PageActivity"/>
        <activity
            android:theme="@style/CustomTheme1"
            android:name="com.example.fitme.Meditation.Stay_Activity"
            android:parentActivityName="com.example.fitme.Meditation_PageActivity"/>
        <activity
            android:theme="@style/CustomTheme1"
            android:name="com.example.fitme.Meditation.Body_Activity"
            android:parentActivityName="com.example.fitme.Meditation_PageActivity"/>
        <activity
            android:theme="@style/C